<script setup lang="ts">
import{computed,ref}from'vue';import{onShow}from'@dcloudio/uni-app';import BottomNav from'../../components/BottomNav.vue';import VisitCard from'../../components/VisitCard.vue';import{registrationApi,type Registration}from'../../api/registration';import{aiApi}from'../../api/ai'
type PrevisitState='none'|'in_progress'|'completed';type Tab='all'|'pending'|'completed'
interface VisitView{registerId:number;patientId?:number;rawStatus?:number;status:string;department:string;doctor:string;date:string;time:string;patient?:string;previsitState?:PrevisitState}
const registrations=ref<Registration[]>([]),previsitStates=ref<Record<number,PrevisitState>>({}),visits=ref<VisitView[]>([]),loading=ref(false),activeTab=ref<Tab>('all')
const filteredVisits=computed(()=>activeTab.value==='all'?visits.value:visits.value.filter(item=>activeTab.value==='completed'?item.rawStatus===3:item.rawStatus!==3&&item.rawStatus!==4))
function canQuery(item:Registration){return item.status!==4}function canStart(item:Registration){return item.status!==3&&item.status!==4}
function open(path:string){if(path==='previsit'){openQuickPrevisit();return}uni.navigateTo({url:path})}
function findRegistration(registerId:number){return registrations.value.find(item=>item.id===registerId)}
function goPrevisitByVisit(item:VisitView){const row=findRegistration(item.registerId);if(row)goPrevisit(row)}
function goPrevisit(item:Registration){uni.navigateTo({url:`/pages/previsit/index?registerId=${item.id}&patientId=${item.patientId||''}`})}
function stateLabel(id:number){return previsitStates.value[id]==='completed'?'查看总结':previsitStates.value[id]==='in_progress'?'继续预问诊':'开始预问诊'}
function openQuickPrevisit(){const rows=registrations.value.filter(item=>item.patientId===currentPatient.value?.patientId&&previsitStates.value[item.id]);if(!rows.length){uni.showModal({title:'暂无可预问诊的挂号',content:'请先为当前就诊人完成挂号。',confirmText:'去挂号',success:r=>r.confirm&&uni.navigateTo({url:'/pages/registration/index'})});return}if(rows.length===1){goPrevisit(rows[0]);return}uni.showActionSheet({itemList:rows.map(item=>`${item.departmentName||'门诊'} · ${item.visitDate||''} · ${stateLabel(item.id)}`),success:r=>goPrevisit(rows[r.tapIndex])})}
async function load(){loading.value=true;try{registrations.value=await registrationApi.managed();const pairs=await Promise.all(registrations.value.filter(canQuery).map(async item=>{try{const data=await aiApi.previsitSession(item.id);if(data?.exists)return[item.id,data.state==='completed'?'completed':'in_progress']as const;if(canStart(item))return[item.id,'none']as const;return null}catch{return null}}));previsitStates.value=Object.fromEntries(pairs.filter((item):item is readonly[number,PrevisitState]=>item!==null));visits.value=registrations.value.map(item=>({registerId:item.id,patientId:item.patientId,rawStatus:item.status,status:item.payStatus===0?'待缴费':item.statusName||'已挂号',department:item.departmentName||'门诊科室',doctor:item.physicianName||'待分配医生',date:item.visitDate||'',time:item.visitTime||'',patient:item.patientName||'患者',previsitState:previsitStates.value[item.id]}))}finally{loading.value=false}}
function detailByVisit(item:VisitView){const row=findRegistration(item.registerId);if(row)row.payStatus===0?open('/pages/payment/index'):open(`/pages/records/index?registerId=${row.id}`)}
onShow(load)
</script>
<style scoped>.visit-page{padding-bottom:calc(190rpx + env(safe-area-inset-bottom))!important}.tabs{margin-top:0!important}</style>
<template><view class="visit-page"><view class="hero"><view class="hero-copy"><view class="hero-title">我的就诊</view><view class="hero-subtitle">挂号、预问诊、病历、报告与缴费</view></view><image class="hero-image" src="/static/patient/management-hero.svg" mode="aspectFit"/></view><view class="content"><view class="tabs card"><view :class="{active:activeTab==='all'}" @tap="activeTab='all'">全部挂号</view><view :class="{active:activeTab==='pending'}" @tap="activeTab='pending'">待就诊</view><view :class="{active:activeTab==='completed'}" @tap="activeTab='completed'">已完成</view></view><view v-if="loading" class="state">正在加载挂号记录…</view><VisitCard v-for="item in filteredVisits" :key="item.registerId" :visit="item" @previsit="goPrevisitByVisit(item)" @action="detailByVisit(item)"/><view v-if="!loading&&!filteredVisits.length" class="state card">当前分类暂无挂号记录</view></view><BottomNav :active="1"/></view></template>
<style scoped lang="scss">.visit-page{min-height:100vh;padding-bottom:145rpx;background:linear-gradient(180deg,#eaf4ff 0,#f6f9ff 360rpx,#f3f6fb 100%);color:#102854}.hero{position:relative;height:255rpx;padding:82rpx 42rpx 0;box-sizing:border-box;overflow:hidden}.hero:after{content:'';position:absolute;right:-60rpx;top:15rpx;width:270rpx;height:270rpx;border-radius:50%;background:rgba(255,255,255,.35)}.hero-copy{position:relative;z-index:2}.hero-title{font-size:42rpx;font-weight:700;letter-spacing:1rpx}.hero-subtitle{margin-top:14rpx;color:#6880a6;font-size:23rpx}.hero-image{position:absolute;z-index:1;right:32rpx;bottom:-12rpx;width:255rpx;height:190rpx;opacity:.92}.content{padding:0 24rpx}.card{border-radius:28rpx;background:rgba(255,255,255,.96);box-shadow:0 12rpx 35rpx rgba(42,91,161,.07)}.quick{padding:30rpx 16rpx 26rpx;display:grid;grid-template-columns:repeat(4,1fr);row-gap:27rpx}.quick-item{display:flex;flex-direction:column;align-items:center;gap:13rpx;color:#172b53;font-size:22rpx}.quick-platform{padding:8rpx;border-radius:25rpx;background:#f4f7fc;box-shadow:inset 0 0 0 1rpx #edf2f8}.tabs{height:76rpx;margin-top:22rpx;padding:0 28rpx;display:flex}.tabs view{position:relative;flex:1;display:flex;align-items:center;justify-content:center;color:#8490a8;font-size:24rpx}.tabs .active{color:#2878ff;font-weight:600}.tabs .active:after{content:'';position:absolute;left:22rpx;right:22rpx;bottom:0;height:5rpx;border-radius:5rpx;background:#2878ff}.state{margin-top:20rpx;padding:45rpx;text-align:center;color:#8d98aa;font-size:21rpx}</style>
