<script setup lang="ts">
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import BottomNav from'../../components/BottomNav.vue';import ServiceIcon from'../../components/ServiceIcon.vue';import VisitCard from'../../components/VisitCard.vue';import{registrationApi,type Registration}from'../../api/registration';import{aiApi}from'../../api/ai';import{currentPatient}from'../../stores/session'
const quick=[['电子病历','/pages/records/index','compose','blue'],['检查报告','/pages/records/index?tab=report','search','blue'],['处方记录','/pages/prescription/index','list','green'],['门诊缴费','/pages/payment/index','wallet-filled','orange'],['AI预问诊','previsit','chat-filled','purple'],['随访管理','/pages/followup/index','notification-filled','orange']]
type PrevisitState='none'|'in_progress'|'completed'
const registrations=ref<Registration[]>([]),previsitStates=ref<Record<number,PrevisitState>>({}),visits=ref<Array<{registerId:number;patientId?:number;status:string;department:string;doctor:string;date:string;time:string;patient?:string;previsitState?:PrevisitState}>>([]),loading=ref(false)
function canQuery(item:Registration){return item.status!==4}
function canStart(item:Registration){return item.status!==3&&item.status!==4}
function open(path:string){if(path==='previsit'){openQuickPrevisit();return}uni.navigateTo({url:path})}
function goPrevisit(item:Registration){uni.navigateTo({url:`/pages/previsit/index?registerId=${item.id}&patientId=${item.patientId||''}`})}
function stateLabel(id:number){return previsitStates.value[id]==='completed'?'已完成':previsitStates.value[id]==='in_progress'?'继续问诊':'开始问诊'}
function openQuickPrevisit(){const rows=registrations.value.filter(item=>item.patientId===currentPatient.value?.patientId&&previsitStates.value[item.id]);if(!rows.length){uni.showModal({title:'暂无可预问诊的挂号',content:'请先为当前就诊人完成挂号。',confirmText:'去挂号',success:r=>r.confirm&&uni.navigateTo({url:'/pages/registration/index'})});return}if(rows.length===1){goPrevisit(rows[0]);return}uni.showActionSheet({itemList:rows.map(item=>`${item.departmentName||'门诊'} · ${item.visitDate||''} · ${stateLabel(item.id)}`),success:r=>goPrevisit(rows[r.tapIndex])})}
async function load(){loading.value=true;try{registrations.value=await registrationApi.managed();const pairs=await Promise.all(registrations.value.filter(canQuery).map(async item=>{try{const data=await aiApi.previsitSession(item.id);if(data?.exists)return[item.id,data.state==='completed'?'completed':'in_progress']as const;if(canStart(item))return[item.id,'none']as const;return null}catch{return null}}));previsitStates.value=Object.fromEntries(pairs.filter((item):item is readonly[number,PrevisitState]=>item!==null));visits.value=registrations.value.map(item=>({registerId:item.id,patientId:item.patientId,status:item.payStatus===0?'待缴费':item.statusName||'待就诊',department:item.departmentName||'门诊科室',doctor:item.physicianName||'待分配医生',date:item.visitDate||'',time:item.visitTime||'',patient:item.patientName||'患者',previsitState:previsitStates.value[item.id]}))}finally{loading.value=false}}
function detail(item:Registration){item.payStatus===0?open('/pages/payment/index'):open('/pages/records/index')}
onShow(load)
</script>
<template><view class="page-shell"><view class="page-title">我的就诊</view><view class="page-subtitle">挂号、预问诊、病历、报告与缴费</view><view class="quick card"><view v-for="item in quick" :key="item[0]" @tap="open(item[1])"><view class="quick-icon-platform"><ServiceIcon :type="item[2]" :tone="item[3]"/></view><text>{{item[0]}}</text></view></view><view class="tabs card"><text class="active">全部挂号</text><text>待就诊</text><text>已完成</text></view><view v-if="loading" class="state">正在加载挂号记录…</view><VisitCard v-for="(item,index) in visits" :key="item.registerId" :visit="item" @previsit="goPrevisit(registrations[index])" @action="detail(registrations[index])"/><view v-if="!loading&&!visits.length" class="state card">暂无挂号记录</view><BottomNav :active="1"/></view></template>
<style scoped lang="scss">.quick{margin-top:28rpx;padding:26rpx 10rpx;display:grid;grid-template-columns:repeat(4,1fr)}.quick>view{display:flex;flex-direction:column;align-items:center;gap:12rpx;font-size:22rpx}.quick-icon-platform{padding:7rpx;border-radius:23rpx;background:#f5f8fd;border:1rpx solid #edf2f8}.state{margin-top:20rpx;padding:45rpx;text-align:center;color:#8d98aa;font-size:21rpx}.tabs{margin-top:22rpx;display:flex}.tabs text{flex:1;padding:27rpx;text-align:center;color:#758098}.tabs .active{color:#2878ff;border-bottom:5rpx solid #2878ff}</style>
