<script setup lang="ts">
import{computed,reactive,ref,watch}from'vue';import{authApi}from'../../api/auth';import AuthField from'../../components/AuthField.vue'
const uni={navigateBack:(options?:any)=>wx.navigateBack(options),showToast:(options:any)=>wx.showToast(options),showModal:(options:any)=>wx.showModal(options)}
const form=reactive({username:'',realName:'',phone:'',idCard:'',password:'',confirmPassword:''}),loading=ref(false),agreed=ref(false),showPassword=ref(false)
function parseChineseIdCard(value:string){const id=value.trim().toUpperCase();if(!/^\d{17}[0-9X]$/.test(id))return null;const dateText=`${id.slice(6,10)}-${id.slice(10,12)}-${id.slice(12,14)}`;const date=new Date(`${dateText}T00:00:00`);if(Number.isNaN(date.getTime())||date.getFullYear()!==Number(id.slice(6,10))||date.getMonth()+1!==Number(id.slice(10,12))||date.getDate()!==Number(id.slice(12,14))||date>new Date()||date.getFullYear()<1900)return null;const weights=[7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2],checks=['1','0','X','9','8','7','6','5','4','3','2'];const sum=weights.reduce((total,weight,index)=>total+Number(id[index])*weight,0);if(id[17]!==checks[sum%11])return null;return{birthdate:dateText,gender:Number(id[16])%2===1?'男':'女'}}
const identity=computed(()=>parseChineseIdCard(form.idCard));const validId=computed(()=>Boolean(identity.value));const gender=computed(()=>identity.value?.gender);const birthdate=computed(()=>identity.value?.birthdate)
watch(()=>form.phone,value=>{if(value.length===11&&!/^1[3-9]\d{9}$/.test(value))uni.showToast({title:'手机号格式不正确',icon:'none'})})
watch(()=>form.idCard,value=>{if(value.length===18){if(!identity.value)uni.showToast({title:'身份证号或校验位不正确',icon:'none',duration:2500});else uni.showToast({title:`已识别：${identity.value.birthdate} ${identity.value.gender}`,icon:'none',duration:2200})}})
function validate(){if(!/^[A-Za-z0-9_]{4,30}$/.test(form.username))return '用户名需为 4-30 位字母、数字或下划线';if(!form.realName.trim())return '请输入真实姓名';if(!/^1[3-9]\d{9}$/.test(form.phone))return '请输入正确的 11 位手机号';if(!validId.value)return '请输入真实有效的 18 位身份证号';if(form.password.length<6)return '密码至少 6 位';if(form.password!==form.confirmPassword)return '两次输入的密码不一致';if(!agreed.value)return '请先阅读并同意用户协议';return ''}
async function submit(){const message=validate();if(message){uni.showToast({title:message,icon:'none',duration:2500});return}loading.value=true;try{await authApi.register({username:form.username.trim(),password:form.password,realName:form.realName.trim(),phone:form.phone,idCard:form.idCard.toUpperCase(),gender:gender.value,birthdate:birthdate.value,userType:'6'});uni.showModal({title:'注册成功',content:'患者档案已创建，请使用新账号登录。',showCancel:false,success:()=>uni.navigateBack()})}catch{}finally{loading.value=false}}
</script>
<template><view class="register-page"><image class="hero-bg" src="/static/auth/hospital-hero.png" mode="aspectFill"/><view class="topbar" @tap="uni.navigateBack()">‹</view><view class="intro"><text class="title">注册账号</text><text class="subtitle">创建您的熙康云医院账号</text><text class="safe">◆ 信息加密保护，安全可靠</text></view><view class="form-card"><AuthField v-model="form.username" label="用户名" icon="○" placeholder="4-30 位字母、数字或下划线"/><AuthField v-model="form.realName" label="真实姓名" icon="证" placeholder="请输入本人姓名"/><AuthField v-model="form.phone" label="手机号" icon="手" type="number" :maxlength="11" placeholder="请输入 11 位手机号"/><AuthField v-model="form.idCard" label="身份证号" icon="卡" :maxlength="18" placeholder="请输入 18 位身份证号"/><AuthField v-model="form.password" label="登录密码" icon="锁" :password="!showPassword" placeholder="请输入至少 6 位密码"><text class="show" @tap="showPassword=!showPassword">{{showPassword?'隐藏':'显示'}}</text></AuthField><AuthField v-model="form.confirmPassword" label="确认密码" icon="锁" password placeholder="请再次输入密码"/><view class="notice"><text>◆</text><view><b>温馨提示</b><text>真实姓名和身份证信息将用于挂号、病历与处方匹配，请确保信息准确无误。</text></view></view><view class="agreement" @tap="agreed=!agreed"><text :class="{checked:agreed}">{{agreed?'✓':''}}</text><view>我已阅读并同意 <b>《用户协议》</b> 和 <b>《隐私政策》</b></view></view><button :loading="loading" @tap="submit">注册账号</button><view class="login-link" @tap="uni.navigateBack()">已有账号，返回登录</view></view><view class="waves"><view/><view/></view></view></template>
<style scoped lang="scss">.register-page{position:relative;min-height:100vh;padding-bottom:55rpx;overflow:hidden;background:#f5faff;color:#10336b}.hero-bg{position:absolute;left:0;top:0;width:100%;height:455rpx;opacity:.82}.topbar{position:relative;z-index:2;padding:calc(var(--status-bar-height) + 12rpx) 38rpx 0;font-size:60rpx;font-weight:300}.intro{position:relative;z-index:1;padding:65rpx 62rpx 65rpx;display:flex;flex-direction:column}.title{font-size:45rpx;font-weight:700;letter-spacing:2rpx}.subtitle{margin-top:13rpx;color:#3d6393;font-size:23rpx}.safe{margin-top:19rpx;color:#5375a1;font-size:20rpx}.form-card{position:relative;z-index:2;margin:0 28rpx;padding:34rpx 34rpx 30rpx;border-radius:34rpx;background:rgba(255,255,255,.98);box-shadow:0 18rpx 50rpx rgba(34,90,158,.13)}.form-card>:deep(.auth-field){margin-bottom:18rpx}.show{padding-left:10rpx;color:#2878ff;font-size:20rpx}.notice{padding:20rpx;display:flex;gap:14rpx;border-radius:18rpx;background:linear-gradient(100deg,#f1f7ff,#f8fbff);color:#5180bf}.notice>text{font-size:23rpx}.notice>view{display:flex;flex-direction:column;gap:7rpx}.notice b{color:#244e85;font-size:20rpx}.notice view text{color:#71839e;font-size:17rpx;line-height:1.55}.agreement{display:flex;gap:12rpx;margin:24rpx 0;color:#7b899f;font-size:18rpx;line-height:1.5}.agreement>text{width:29rpx;height:29rpx;flex:none;border:2rpx solid #b4c1d2;border-radius:6rpx;text-align:center;line-height:27rpx}.agreement>text.checked{border-color:#2878ff;background:#2878ff;color:#fff}.agreement b{color:#2580f5;font-weight:500}.form-card button{height:82rpx;border-radius:20rpx;background:linear-gradient(105deg,#3c91ff,#2879f5);box-shadow:0 12rpx 25rpx rgba(38,121,242,.2);color:#fff;font-size:28rpx;font-weight:600}.login-link{padding-top:23rpx;text-align:center;color:#2878ff;font-size:20rpx}.waves{position:absolute;left:-10%;right:-10%;bottom:-45rpx;height:130rpx;opacity:.3}.waves view{height:70rpx;border-top:3rpx solid #62aaff;border-radius:50%;transform:rotate(4deg)}.waves view:last-child{transform:rotate(-4deg)}</style>
