<script setup lang="ts">
import{ref}from'vue';import{onShow}from'@dcloudio/uni-app';import PageHeader from'../../components/PageHeader.vue';import{patientApi}from'../../api/patient';import{session,saveSession,type PatientInfo}from'../../stores/session'
const patients=ref<PatientInfo[]>([]),loading=ref(false)
function maskPhone(phone?:string){return phone?phone.replace(/(\d{3})\d{4}(\d{4})/,'$1****$2'):'未填写手机号'}
async function load(){if(!session.userId)return;loading.value=true;try{patients.value=await patientApi.list(session.userId);saveSession({patients:patients.value})}finally{loading.value=false}}
function open(item?:PatientInfo){uni.navigateTo({url:item?`/pages/patient-form/index?id=${item.patientId}`:'/pages/patient-form/index'})}
onShow(load)
</script>
<template><view class="page-shell"><PageHeader title="就诊人管理" subtitle="管理本人及家属就诊信息"/><view class="notice">就诊人信息将用于挂号、缴费和病历查询，请确保真实准确。</view><view v-if="loading" class="notice">正在加载就诊人…</view><view v-for="item in patients" :key="item.patientId" class="patient card" @tap="open(item)"><view class="avatar">{{item.realName.slice(0,1)}}</view><view><view><text>{{item.realName}}</text><text>{{item.relation||'家属'}}</text><text v-if="item.isPrimary===1">默认</text></view><text>{{maskPhone(item.phone)}}</text><text class="verified">✓ 已实名认证</text></view><text class="edit">编辑 ›</text></view><view v-if="!loading&&!patients.length" class="notice">暂无就诊人信息</view><button class="add" @tap="open()">＋ 添加就诊人</button><view class="section card"><view class="section-title">温馨提示</view><text class="tip">未成年人和老年人可以由家属代为管理，身份信息请与证件保持一致。</text></view></view></template>
<style scoped lang="scss">.notice{padding:19rpx 22rpx;border-radius:18rpx;background:#eaf3ff;color:#4177be;font-size:21rpx;line-height:1.6}.patient{margin-top:18rpx;padding:25rpx;display:flex;align-items:center}.avatar{width:78rpx;height:78rpx;border-radius:50%;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#72c8ff,#3478ef);color:#fff;font-size:27rpx}.patient>view:nth-child(2){flex:1;margin-left:18rpx;display:flex;flex-direction:column;gap:7rpx;color:#7d899c;font-size:20rpx}.patient>view:nth-child(2)>view{display:flex;align-items:center;gap:9rpx}.patient>view:nth-child(2)>view text:first-child{color:#102450;font-size:27rpx;font-weight:700}.patient>view:nth-child(2)>view text:not(:first-child){padding:4rpx 9rpx;border-radius:12rpx;background:#edf3fb;color:#62728d;font-size:17rpx}.verified{color:#12a47d}.edit{color:#2878ff;font-size:21rpx}.add{margin-top:24rpx;border:2rpx dashed #75aaff;background:#edf5ff;color:#2878ff}.tip{display:block;margin-top:18rpx;color:#7b879b;font-size:21rpx;line-height:1.7}</style>
