<script setup lang="ts">
import BottomNav from '../../components/BottomNav.vue'
import ServiceIcon from '../../components/ServiceIcon.vue'
const primary=[['chat-filled','AI 导诊','green','/pages/triage/index'],['staff-filled','按科室挂号','blue','/pages/registration/index'],['compose','病历报告','orange','/pages/records/index']]
const services=[['calendar','预约挂号','blue','/pages/registration/index'],['calendar-filled','当日挂号','green','/pages/registration/index?mode=today'],['notification-filled','排队叫号','orange','/pages/queue/index'],['notification','候诊查询','purple','/pages/queue/index'],['wallet-filled','门诊缴费','orange','/pages/payment/index'],['compose','病历报告','blue','/pages/records/index'],['person-filled','就诊人管理','purple','/pages/patients/index']]
function open(path:string){uni.navigateTo({url:path})}
</script>
<template><view class="page-shell"><view class="hospital-name">熙康医院</view><view class="hero card"><text class="hero-title">云端守护 · 健康相伴</text><text class="hero-tag">熙康云医院</text><text class="hero-desc">让医疗和护理服务到家</text><view class="buildings"><view/><view/><view/></view></view><view class="primary"><view v-for="item in primary" :key="item[1]" class="card primary-item" @tap="open(item[3])"><ServiceIcon :type="item[0]" :tone="item[2]" size="large"/><text class="primary-title">{{item[1]}}</text><text class="primary-desc">便捷医疗服务</text></view></view><view class="card section"><view class="section-head"><text class="section-title">门诊服务</text><text class="section-more">已接入服务</text></view><view class="service-grid"><view v-for="item in services" :key="item[1]" class="service-item" @tap="open(item[3])"><view class="icon-platform"><ServiceIcon :type="item[0]" :tone="item[2]"/></view><text class="service-label">{{item[1]}}</text></view></view></view><view class="service-note card"><ServiceIcon type="heart-filled" tone="blue"/><view><text>熙康就医服务</text><text>覆盖导诊、挂号、候诊、缴费、病历和就诊人管理</text></view></view><BottomNav :active="0"/></view></template>
<style scoped lang="scss">.hospital-name{font-size:38rpx;font-weight:800;margin:14rpx 4rpx 30rpx}.hero{height:280rpx;padding:45rpx 28rpx;display:flex;flex-direction:column;gap:18rpx;overflow:hidden;position:relative;background:linear-gradient(125deg,#bfe1ff,#82bcf4)}.hero-title{font-size:38rpx;font-weight:800;color:#1357a5}.hero-tag{font-size:29rpx;color:#14529a}.hero-desc{font-size:24rpx;color:#38699d}.buildings{position:absolute;right:15rpx;bottom:0;display:flex;align-items:flex-end;gap:8rpx}.buildings view{width:52rpx;height:135rpx;background:repeating-linear-gradient(90deg,rgba(255,255,255,.75) 0 7rpx,rgba(42,115,184,.25) 8rpx 13rpx)}.buildings view:nth-child(2){height:190rpx}.buildings view:nth-child(3){height:110rpx}.primary{display:grid;grid-template-columns:repeat(3,1fr);gap:14rpx;margin-top:24rpx}.primary-item{padding:25rpx 5rpx 23rpx;display:flex;flex-direction:column;align-items:center;gap:10rpx}.primary-title{font-size:24rpx;font-weight:650}.primary-desc{font-size:17rpx;color:#9aa3b2}.icon-platform{padding:8rpx;border:1rpx solid #edf3fb;border-radius:24rpx;background:linear-gradient(145deg,#fff,#f4f8fd);box-shadow:0 7rpx 17rpx rgba(55,91,150,.07)}.service-note{margin-top:24rpx;padding:25rpx;display:flex;align-items:center;gap:18rpx;background:linear-gradient(120deg,#edf6ff,#d4e7ff)}.service-note>view:last-child{display:flex;flex-direction:column;gap:8rpx}.service-note>view:last-child text:first-child{font-size:27rpx;font-weight:700}.service-note>view:last-child text:last-child{color:#617799;font-size:20rpx}</style>
