<script setup lang="ts">
import{computed,reactive,ref,watch}from'vue';import{onLoad}from'@dcloudio/uni-app';import PageHeader from'../../components/PageHeader.vue';import{patientApi}from'../../api/patient';import{session}from'../../stores/session'
const patientId=ref(0),saving=ref(false),editing=computed(()=>patientId.value>0),relations=['配偶','子女','父母','其他']
const form=reactive({realName:'',relation:'配偶',idCard:'',phone:'',homeAddress:'',allergyHistory:''})
function parseChineseIdCard(value:string){const id=value.trim().toUpperCase();const provinces=new Set(['11','12','13','14','15','21','22','23','31','32','33','34','35','36','37','41','42','43','44','45','46','50','51','52','53','54','61','62','63','64','65','71','81','82']);if(id.length!==18||!/^\d{17}[0-9X]$/.test(id)||!provinces.has(id.slice(0,2))||id.slice(0,6)==='000000'||id.slice(14,17)==='000')return null;const birthdate=`${id.slice(6,10)}-${id.slice(10,12)}-${id.slice(12,14)}`;const date=new Date(`${birthdate}T00:00:00`);if(Number.isNaN(date.getTime())||date.getFullYear()!==Number(id.slice(6,10))||date.getMonth()+1!==Number(id.slice(10,12))||date.getDate()!==Number(id.slice(12,14))||date>new Date()||date.getFullYear()<1900)return null;const weights=[7,9,10,5,8,4,2,1,6,3,7,9,10,5,8,4,2],checks=['1','0','X','9','8','7','6','5','4','3','2'];const sum=weights.reduce((total,weight,index)=>total+Number(id[index])*weight,0);if(id.charAt(17)!==checks[sum%11])return null;return{birthdate,gender:Number(id.charAt(16))%2===1?'男':'女'}}
const identity=computed(()=>parseChineseIdCard(form.idCard));const idError=computed(()=>form.idCard.length===18&&!identity.value);const phoneError=computed(()=>form.phone.length===11&&!/^1[3-9]\d{9}$/.test(form.phone))
function selectRelation(e:any){form.relation=relations[Number(e.detail.value)]}
watch(()=>form.idCard,value=>{if(value.length===18)uni.showToast({title:identity.value?`已识别：${identity.value.birthdate} ${identity.value.gender}`:'身份证号或校验位不正确',icon:'none',duration:2200})})
watch(()=>form.phone,value=>{if(value.length===11&&phoneError.value)uni.showToast({title:'手机号格式不正确',icon:'none'})})
function validate(){if(!form.realName.trim())return '请填写真实姓名';if(!identity.value)return '请填写真实有效的 18 位身份证号';if(!/^1[3-9]\d{9}$/.test(form.phone))return '请填写正确的 11 位手机号';return ''}
async function save(){const message=validate();if(message){uni.showToast({title:message,icon:'none',duration:2500});return}saving.value=true;try{const data={realName:form.realName.trim(),gender:identity.value!.gender,idCard:form.idCard.toUpperCase(),birthdate:identity.value!.birthdate,phone:form.phone,homeAddress:form.homeAddress||undefined,allergyHistory:form.allergyHistory||undefined};if(editing.value)await patientApi.update(patientId.value,data);else await patientApi.addFamily(session.userId,form.relation,data);uni.showToast({title:editing.value?'保存成功':'添加成功',icon:'success'});setTimeout(()=>uni.navigateBack(),500)}catch{}finally{saving.value=false}}
onLoad(async options=>{patientId.value=Number(options?.id||0);if(!patientId.value)return;const data=await patientApi.detail(patientId.value);Object.assign(form,{realName:data.realName||'',relation:data.relation||'家属',idCard:data.idCard||'',phone:data.phone||'',homeAddress:data.homeAddress||'',allergyHistory:data.allergyHistory||''})})
</script>
<template><view class="page-shell"><PageHeader :title="editing?'编辑就诊人':'添加就诊人'" subtitle="身份信息将用于挂号与病历匹配"/><view class="identity-tip"><text>i</text><text>出生日期和性别将根据身份证自动识别，无需手动填写。</text></view><view class="form-card card"><view class="field"><text><i>*</i> 姓名</text><input v-model="form.realName" maxlength="30" placeholder="请输入真实姓名"/></view><picker v-if="!editing" :range="relations" @change="selectRelation"><view class="field"><text><i>*</i> 与本人关系</text><text class="value">{{form.relation}} ›</text></view></picker><view class="field" :class="{invalid:idError}"><text><i>*</i> 身份证号</text><input v-model="form.idCard" maxlength="18" placeholder="请输入 18 位身份证号"/></view><text v-if="idError" class="error">身份证号、出生日期或校验位不正确</text><view class="derived"><view><text>性别</text><text>{{identity?.gender||'待识别'}}</text></view><view><text>出生日期</text><text>{{identity?.birthdate||'待识别'}}</text></view></view><view class="field" :class="{invalid:phoneError}"><text><i>*</i> 手机号</text><input v-model="form.phone" type="number" maxlength="11" placeholder="请输入 11 位手机号"/></view><text v-if="phoneError" class="error">请输入正确的中国大陆手机号</text><view class="field"><text>家庭住址</text><input v-model="form.homeAddress" maxlength="100" placeholder="请输入家庭住址"/></view><view class="textarea-field"><text>过敏史</text><textarea v-model="form.allergyHistory" maxlength="300" placeholder="无过敏史可不填"/></view></view><button class="submit" :loading="saving" @tap="save">{{saving?'正在保存…':'保存就诊人'}}</button></view></template>
<style scoped lang="scss">.identity-tip{margin-bottom:20rpx;padding:18rpx 21rpx;display:flex;align-items:center;gap:12rpx;border-radius:17rpx;background:#eaf3ff;color:#537096;font-size:20rpx;line-height:1.5}.identity-tip text:first-child{width:27rpx;height:27rpx;flex:none;border-radius:50%;background:#3184f5;color:#fff;text-align:center;line-height:27rpx}.form-card{padding:5rpx 27rpx}.field{min-height:96rpx;display:flex;align-items:center;border-bottom:1rpx solid #edf1f6;font-size:24rpx}.field.invalid{border-bottom-color:#ef6570}.field>text:first-child{width:205rpx;color:#263a5f}.field i{color:#ef5360;font-style:normal}.field input{flex:1;text-align:right;font-size:23rpx}.value{flex:1;text-align:right;color:#65738b}.error{display:block;padding:9rpx 0;color:#e94f5c;font-size:18rpx;text-align:right}.derived{margin:15rpx 0;padding:18rpx;display:grid;grid-template-columns:1fr 1fr;gap:10rpx;border-radius:16rpx;background:#f3f8ff}.derived view{display:flex;flex-direction:column;align-items:center}.derived text:first-child{color:#8290a5;font-size:17rpx}.derived text:last-child{margin-top:5rpx;color:#2878ff;font-size:22rpx;font-weight:600}.textarea-field{padding:25rpx 0}.textarea-field>text{font-size:24rpx;color:#263a5f}.textarea-field textarea{box-sizing:border-box;width:100%;height:150rpx;margin-top:17rpx;padding:18rpx;border-radius:18rpx;background:#f5f8fc;font-size:23rpx}.submit{height:88rpx;margin-top:28rpx;border-radius:25rpx;background:linear-gradient(100deg,#2878ff,#5ba4ff);color:#fff;font-size:28rpx}</style>
