<script setup lang="ts">
import{ref,onMounted}from'vue';import{authApi}from'../../api/auth';import{saveSession}from'../../stores/session';import ServiceIcon from'../../components/ServiceIcon.vue'
const username=ref('');const password=ref('');const captchaCode=ref('');const captchaId=ref('');const captchaImage=ref('');const loading=ref(false)
async function loadCaptcha(){try{const data=await authApi.captcha();captchaId.value=data.captchaId;captchaImage.value=data.imageBase64.startsWith('data:')?data.imageBase64:`data:image/png;base64,${data.imageBase64}`}catch{captchaImage.value=''}}
async function login(){if(!username.value||!password.value||!captchaCode.value){uni.showToast({title:'请完整填写登录信息',icon:'none'});return}loading.value=true;try{const data=await authApi.login({username:username.value.trim(),password:password.value,captchaId:captchaId.value,captchaCode:captchaCode.value.trim()});if(data.role!=='patient'&&data.role!=='admin')throw new Error('当前账号不是患者账号');saveSession({...data,currentPatientId:data.patients?.find(item=>item.isPrimary===1)?.patientId||data.patients?.[0]?.patientId||null});uni.reLaunch({url:'/pages/home/index'})}catch(error){captchaCode.value='';await loadCaptcha();const message=error instanceof Error?error.message:'登录失败';uni.showToast({title:message,icon:'none'})}finally{loading.value=false}}
onMounted(loadCaptcha)
</script>
<template><view class="login-page"><view class="brand"><view class="brand-icon"><ServiceIcon type="heart" tone="blue" size="large"/></view><text class="brand-name">熙康云医院</text><text class="brand-desc">患者端 · 让医疗和护理服务到家</text></view><view class="login-card"><text class="title">欢迎登录</text><text class="subtitle">请使用患者账号登录</text><view class="field"><text>账号</text><input v-model="username" placeholder="请输入用户名"/></view><view class="field"><text>密码</text><input v-model="password" password placeholder="请输入密码"/></view><view class="captcha-row"><view class="field"><text>验证码</text><input v-model="captchaCode" maxlength="6" placeholder="请输入验证码" confirm-type="done" @confirm="login"/></view><image v-if="captchaImage" :src="captchaImage" mode="aspectFit" @tap="loadCaptcha"/><view v-else class="captcha-empty" @tap="loadCaptcha">点击刷新</view></view><button :loading="loading" @tap="login">登录</button><text class="tip">登录即代表您同意平台隐私保护与用户协议</text></view></view></template>
<style scoped lang="scss">.login-page{min-height:100vh;padding:calc(var(--status-bar-height) + 90rpx) 40rpx 60rpx;background:radial-gradient(circle at 75% 5%,#9dccff,transparent 35%),linear-gradient(180deg,#dcecff,#f5f8fd)}.brand{display:flex;flex-direction:column;align-items:center}.brand-icon{padding:10rpx;border-radius:30rpx;background:rgba(255,255,255,.55)}.brand-name{margin-top:20rpx;font-size:42rpx;font-weight:600}.brand-desc{margin-top:10rpx;color:#687b9a;font-size:22rpx}.login-card{margin-top:55rpx;padding:38rpx 32rpx;border-radius:34rpx;background:rgba(255,255,255,.96);box-shadow:0 20rpx 55rpx rgba(44,96,174,.13)}.title{display:block;font-size:34rpx;font-weight:600}.subtitle{display:block;margin:8rpx 0 28rpx;color:#8994a7;font-size:21rpx}.field{margin-top:18rpx}.field>text{display:block;margin-bottom:10rpx;color:#53627c;font-size:21rpx}.field input{height:82rpx;padding:0 22rpx;border:1rpx solid #e4eaf3;border-radius:20rpx;background:#f8fafd;font-size:24rpx}.captcha-row{display:grid;grid-template-columns:1fr 210rpx;gap:15rpx;align-items:end}.captcha-row image,.captcha-empty{width:210rpx;height:82rpx;border-radius:18rpx;background:#f3f7fc}.captcha-empty{display:flex;align-items:center;justify-content:center;color:#2878ff;font-size:20rpx}.login-card button{margin-top:32rpx;height:88rpx;border-radius:24rpx;background:linear-gradient(100deg,#2773f1,#59a0ff);color:#fff;font-size:28rpx}.tip{display:block;margin-top:22rpx;text-align:center;color:#a0a9b8;font-size:18rpx}</style>
