<script setup lang="ts">
import { onMounted } from 'vue'
import { unreadMessageCount, refreshUnreadMessageCount } from '../stores/notification'
import { replacePage } from '../utils/navigation'
const props=defineProps<{active:number}>()
const items=[{text:'首页',path:'/pages/home/index',icon:'home'},{text:'我的就诊',path:'/pages/visits/index',icon:'visit'},{text:'消息中心',path:'/pages/messages/index',icon:'message'},{text:'医院信息',path:'/pages/hospital/index',icon:'hospital'},{text:'个人中心',path:'/pages/profile/index',icon:'profile'}]
function go(index:number,path:string){if(index===props.active)return;replacePage(path)}
onMounted(refreshUnreadMessageCount)
</script>
<template><view class="bottom-nav"><view v-for="(item,index) in items" :key="item.path" class="nav-item" :class="{active:index===active}" @tap="go(index,item.path)"><view class="nav-icon"><image class="nav-icon-img" :src="`/static/nav/${item.icon}${index===active?'-active':''}.svg`" mode="aspectFit"/><text v-if="index===2&&unreadMessageCount>0" class="badge">{{unreadMessageCount>99?'99+':unreadMessageCount}}</text></view><text class="nav-label">{{item.text}}</text></view></view></template>
<style scoped lang="scss">.bottom-nav{position:fixed;z-index:99;left:28rpx;right:28rpx;bottom:calc(24rpx + env(safe-area-inset-bottom));height:104rpx;padding:0 12rpx;display:flex;align-items:center;background:rgba(255,255,255,.96);border:1rpx solid rgba(232,240,250,.95);border-radius:44rpx;box-shadow:0 18rpx 48rpx rgba(43,86,152,.14);box-sizing:border-box;backdrop-filter:blur(12px)}.nav-item{position:relative;flex:1;height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#8793aa}.nav-icon{position:relative;width:43rpx;height:43rpx;display:flex;align-items:center;justify-content:center}.nav-icon-img{width:100%;height:100%}.nav-label{margin-top:7rpx;font-size:19rpx;line-height:1}.active .nav-icon{width:70rpx;height:58rpx;margin-top:-28rpx;border-radius:25rpx;background:#fff;box-shadow:0 10rpx 28rpx rgba(37,116,255,.16)}.active .nav-icon-img{width:43rpx;height:43rpx}.active .nav-label{margin-top:8rpx;color:#2878ff;font-weight:650}.badge{position:absolute;right:-16rpx;top:-9rpx;min-width:27rpx;height:27rpx;padding:0 5rpx;border:3rpx solid #fff;border-radius:20rpx;background:#ff4c55;color:#fff;font-size:16rpx;line-height:27rpx;text-align:center;box-sizing:border-box}</style>
