
export * from './request'
export * from './result'
export * from './modules/auth'
export { registrationApi } from './modules/registration'
export * from './modules/physician'
export * from './modules/medtech'
export * from './modules/pharmacy'
export * from './modules/ai'
export * from './modules/common'
export * from './modules/patient'
export * from './modules/schedule'
export * from './modules/admin'
export * from './modules/resultForm'
