<script setup lang="ts">
import BottomNav from '../../components/BottomNav.vue'
import ServiceIcon from '../../components/ServiceIcon.vue'
import{currentPatient,session}from'../../stores/session'
const functions=[['挂号记录','/pages/visits/index','calendar','blue'],['门诊缴费','/pages/payment/index','wallet-filled','orange'],['病历报告','/pages/records/index','compose','blue'],['处方记录','/pages/prescription/index','list','green'],['预约挂号','/pages/registration/index','calendar-filled','green'],['AI预问诊','/pages/previsit/index','chat-filled','purple'],['随访管理','/pages/followup/index','notification-filled','orange'],['就诊人管理','/pages/patients/index','person-filled','purple']]
function open(path:string){if(path==='/pages/visits/index')uni.reLaunch({url:path});else uni.navigateTo({url:path})}
</script>
<template><view class="page-shell"><view class="page-title">个人中心</view><view class="profile-hero"><view class="user"><view class="avatar"><view/><view/></view><view class="identity"><view><text class="name">{{currentPatient?.realName||session.realName||'患者'}}</text><text class="verified">✓ 已实名认证</text></view><text>{{currentPatient?.phone||'手机号未填写'}}</text></view><text class="setting">账户设置 ›</text></view><view class="account-stats"><view><text>{{session.patients.length}}人</text><text>就诊人管理</text></view><view><text>¥{{Number(currentPatient?.accountBalance||0).toFixed(2)}}</text><text>账户余额</text></view><view><text>4张</text><text>我的处方</text></view><view><text>2项</text><text>随访计划</text></view></view></view><view class="section card"><view class="section-title mark">医疗服务</view><view class="service-grid"><view v-for="item in functions" :key="item[0]" class="service-item" @tap="open(item[1])"><view class="profile-icon-platform"><ServiceIcon :type="item[2]" :tone="item[3]"/></view><text class="service-label">{{item[0]}}</text></view></view></view><view class="safe-card card"><view class="safe-icon">✓</view><view><text>个人医疗信息安全保护中</text><text>数据仅用于您的就医服务</text></view></view><BottomNav :active="4"/></view></template>
<style scoped lang="scss">.profile-hero{margin-top:30rpx;padding:32rpx 22rpx 18rpx;border-radius:34rpx;background:linear-gradient(135deg,#cce6ff,#75a7ed);box-shadow:0 18rpx 40rpx rgba(55,116,206,.2)}.user{display:flex;align-items:center}.avatar{position:relative;width:96rpx;height:96rpx;border-radius:50%;background:#fff}.avatar view:first-child{position:absolute;left:34rpx;top:20rpx;width:29rpx;height:29rpx;border-radius:50%;background:#4b9bf2}.avatar view:last-child{position:absolute;left:24rpx;bottom:17rpx;width:49rpx;height:29rpx;border-radius:30rpx 30rpx 14rpx 14rpx;background:#4b9bf2}.identity{flex:1;margin-left:20rpx;display:flex;flex-direction:column;gap:12rpx;color:#294d83;font-size:25rpx}.identity>view{display:flex;align-items:center;gap:12rpx}.name{font-size:34rpx;font-weight:750;color:#082363}.verified{white-space:nowrap;padding:5rpx 12rpx;border-radius:22rpx;background:#effffb;color:#18a98f;font-size:19rpx}.setting{width:154rpx;padding:14rpx 8rpx;border-radius:30rpx;text-align:center;background:rgba(255,255,255,.68);color:#526d95;font-size:21rpx}.account-stats{margin-top:26rpx;padding:24rpx 4rpx;border-radius:25rpx;display:grid;grid-template-columns:repeat(4,1fr);background:#fff}.account-stats view{display:flex;flex-direction:column;align-items:center;gap:9rpx;text-align:center;font-size:19rpx}.account-stats view text:first-child{color:#2878ff;font-size:25rpx} .profile-icon-platform{padding:7rpx;border-radius:23rpx;background:#f6f9fd;border:1rpx solid #edf2f8}.mark{margin-bottom:30rpx;padding-left:15rpx;border-left:7rpx solid #3f8dff}.safe-card{margin-top:24rpx;padding:25rpx;display:flex;align-items:center;background:linear-gradient(120deg,#edf7ff,#dcecff)}.safe-icon{width:60rpx;height:60rpx;border-radius:20rpx;display:flex;align-items:center;justify-content:center;background:#2878ff;color:#fff}.safe-card>view:last-child{margin-left:16rpx;display:flex;flex-direction:column;gap:7rpx}.safe-card>view:last-child text:first-child{font-size:23rpx;font-weight:650}.safe-card>view:last-child text:last-child{color:#7d899c;font-size:19rpx}</style>
