<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import PageHeader from '../../components/PageHeader.vue'
import ServiceIcon from '../../components/ServiceIcon.vue'
import { registrationApi, type Registration } from '../../api/registration'
import { currentPatient } from '../../stores/session'

const loading = ref(false)
const registrations = ref<Registration[]>([])
const current = computed(() => registrations.value.find(item => item.patientId === currentPatient.value?.patientId && item.status !== 3 && item.status !== 4) || null)
async function load(){ loading.value=true; try{ registrations.value=await registrationApi.managed() || [] }finally{ loading.value=false } }
async function checkin(){if(!current.value)return;uni.showModal({title:'确认报到',content:`${current.value.departmentName||'门诊'} · ${current.value.visitDate||''} ${current.value.visitTime||''}`,success:async r=>{if(!r.confirm)return;try{await registrationApi.checkIn(current.value!.id);uni.showToast({title:'报到成功',icon:'success'});await load()}catch{}}})}
onShow(load)
</script>
<template><view class="page-shell"><PageHeader title="候诊查询" subtitle="查看挂号安排并完成到院报到"/><view v-if="loading" class="empty card">正在加载…</view><view v-else-if="!current" class="empty card">当前就诊人暂无待就诊挂号</view><template v-else><view class="queue-hero card"><text>{{current.checkedIn?'已到院报到':'待到院报到'}}</text><text>{{current.caseNumber||`挂号 ${current.id}`}}</text><text>{{current.departmentName||'门诊科室'}}</text><view class="progress"><view :style="{width:current.checkedIn?'100%':'35%'}"/></view><text>{{current.visitDate}} {{current.visitTime}}</text></view><view class="visit card"><view class="visit-head"><text>{{current.statusName||'待就诊'}}</text><text>{{current.payStatusName||''}}</text></view><view class="visit-body"><view class="queue-icon-platform"><ServiceIcon type="registration" tone="blue" size="large"/></view><view><text>{{current.departmentName||'门诊科室'}}</text><text>{{current.physicianName||'医生待定'}}</text><text>{{current.patientName||currentPatient?.realName}}</text></view></view><button :disabled="current.checkedIn" @tap="checkin">{{current.checkedIn?'已完成报到':'到院报到'}}</button></view></template><view class="section card"><view class="section-title">就诊提示</view><view v-for="(tip,index) in ['请提前 20 分钟到院','留意叫号信息','过号后请联系分诊台']" :key="tip" class="tips"><text>{{index+1}}</text><view><text>{{tip}}</text><text>如有疑问请咨询现场工作人员</text></view></view></view></view></template>
<style scoped lang="scss">.queue-hero{padding:32rpx;display:flex;flex-direction:column;align-items:center;background:linear-gradient(135deg,#4289f7,#70b7ff);color:#fff}.queue-hero>text:first-child{font-size:22rpx;opacity:.85}.queue-hero>text:nth-child(2){margin-top:12rpx;font-size:38rpx;font-weight:800}.queue-hero>text:nth-child(3){margin-top:9rpx;font-size:26rpx}.queue-hero>text:last-child{font-size:20rpx;opacity:.9}.progress{width:80%;height:10rpx;margin:25rpx 0 12rpx;border-radius:8rpx;background:rgba(255,255,255,.3)}.progress view{height:100%;border-radius:8rpx;background:#fff}.queue-icon-platform{padding:7rpx;border-radius:25rpx;background:#f4f8ff}.visit{margin-top:22rpx;padding:26rpx}.visit-head{display:flex;justify-content:space-between;color:#718099;font-size:21rpx}.visit-head text:first-child{color:#12a67d}.visit-body{display:flex;align-items:center;padding:25rpx 0}.visit-body>view:last-child{margin-left:18rpx;display:flex;flex-direction:column;gap:8rpx;color:#7d899c;font-size:21rpx}.visit-body>view:last-child text:first-child{color:#112650;font-size:28rpx;font-weight:700}.visit button{background:#2878ff;color:#fff}.tips{display:flex;align-items:center;margin-top:24rpx}.tips>text{width:48rpx;height:48rpx;border-radius:50%;display:flex;align-items:center;justify-content:center;background:#eaf3ff;color:#2878ff}.tips view{margin-left:16rpx;display:flex;flex-direction:column;gap:6rpx}.tips view text:first-child{font-size:24rpx}.tips view text:last-child{color:#8894a7;font-size:20rpx}.empty{padding:80rpx 20rpx;text-align:center;color:#8b97aa;font-size:23rpx}</style>
