<script setup lang="ts">
import{nextTick,ref}from'vue';import{onLoad}from'@dcloudio/uni-app';import PageHeader from'../../components/PageHeader.vue';import{aiApi,type PrevisitSummary,type TriageSummary}from'../../api/ai';import{currentPatient}from'../../stores/session';import{registrationApi,type Registration}from'../../api/registration'
interface Message{role:'ai'|'user'|'system';content:string}
const answer=ref(''),messages=ref<Message[]>([]),sessionUuid=ref(''),loading=ref(false),finished=ref(false),register=ref<Registration|null>(null),scrollTop=ref(0),summary=ref<PrevisitSummary|null>(null),triageSummary=ref<TriageSummary|null>(null)
function push(role:Message['role'],content:string){messages.value.push({role,content});nextTick(()=>scrollTop.value+=10000)}
function append(text:string){const last=messages.value[messages.value.length-1];if(last?.role==='ai')last.content+=text;nextTick(()=>scrollTop.value+=1000)}
async function finish(){finished.value=true;summary.value=await aiApi.previsitFinish(sessionUuid.value);push('system',`预问诊已完成\n主诉：${summary.value.chiefComplaint||'—'}\n症状时长：${summary.value.symptomDuration||'—'}\n过敏史：${summary.value.allergySummary||'—'}`)}
async function start(registerId:number,patientId:number,triageSessionId?:string){loading.value=true;try{const existing=await aiApi.previsitSession(registerId);if(existing?.exists){sessionUuid.value=existing.sessionUuid||'';(existing.rounds||[]).forEach(round=>{if(round.aiQuestion)push('ai',round.aiQuestion);if(round.patientAnswer)push('user',round.patientAnswer)});finished.value=existing.state==='completed';if(finished.value&&existing.summary){summary.value=existing.summary as PrevisitSummary;push('system',`预问诊已完成\n主诉：${summary.value.chiefComplaint||'—'}\n症状时长：${summary.value.symptomDuration||'—'}\n过敏史：${summary.value.allergySummary||'—'}`)}return}push('ai','');const meta=await aiApi.previsitStart({registerId,patientId,triageSessionId},append);sessionUuid.value=meta.sessionUuid||'';if(meta.finished)await finish()}catch(error){const message=error instanceof Error?error.message:'预问诊启动失败';const last=messages.value[messages.value.length-1];if(last?.role==='ai'&&!last.content)last.content=message;else push('system',message)}finally{loading.value=false}}
async function send(){const text=answer.value.trim();if(!text||loading.value||finished.value||!sessionUuid.value)return;answer.value='';push('user',text);push('ai','');loading.value=true;try{const meta=await aiApi.previsitReply({sessionUuid:sessionUuid.value,answer:text},append);if(meta.finished)await finish()}catch(error){messages.value[messages.value.length-1].content=error instanceof Error?error.message:'回复失败，请重试'}finally{loading.value=false}}
onLoad(async options=>{let id=Number(options?.registerId||0);const all=await registrationApi.managed();register.value=all.find(item=>item.id===id)||all.find(item=>item.patientId===currentPatient.value?.patientId&&item.status!==3&&item.status!==4)||null;if(!register.value){push('system','暂无可进行预问诊的挂号记录，请先完成挂号。');return}try{triageSummary.value=await aiApi.triageSummaryByRegister(register.value.id)}catch{triageSummary.value=null}const patientId=Number(register.value.patientId||options?.patientId||currentPatient.value?.patientId);if(!patientId){push('system','该挂号记录缺少就诊人信息，无法开始预问诊。');return}await start(register.value.id,patientId,String(options?.triageSessionId||'')||undefined)})
</script>
<template><view class="page-shell chat-page"><PageHeader title="AI 预问诊" subtitle="挂号后提前整理病情信息"/><view v-if="register" class="visit-info card"><view class="icon-box blue">诊</view><view><text>{{register.departmentName||'门诊科室'}} · {{register.physicianName||'待分配医生'}}</text><text>{{register.visitDate}} {{register.visitTime}}</text></view><text>{{finished?'已完成':'进行中'}}</text></view><view v-if="triageSummary" class="triage-card card"><view class="triage-title"><text>✓ 已关联本次 AI 导诊</text><text>{{triageSummary.riskLevel==='critical'?'高风险':triageSummary.riskLevel==='urgent'?'需尽快就医':'普通'}}</text></view><view class="triage-main">{{triageSummary.symptomDescription||'导诊症状信息已载入'}}</view><view class="triage-dept">推荐科室：{{triageSummary.recommendDeptName||register?.departmentName||'—'}}</view></view><scroll-view class="chat" scroll-y :scroll-top="scrollTop"><view v-for="(item,index) in messages" :key="index" class="message" :class="item.role"><view v-if="item.role==='ai'" class="ai-avatar">AI</view><text>{{item.content||(loading?'正在思考…':'')}}</text></view></scroll-view><view v-if="register&&!finished" class="composer"><input v-model="answer" :disabled="loading" confirm-type="send" :placeholder="loading?'请稍候…':'请输入回答'" @confirm="send"/><view @tap="send">发送</view></view></view></template>
<style scoped lang="scss">.chat-page{padding-bottom:145rpx}.visit-info{padding:20rpx;display:flex;align-items:center}.visit-info>view:nth-child(2){flex:1;margin-left:15rpx;display:flex;flex-direction:column;gap:7rpx}.visit-info>view:nth-child(2) text:first-child{font-size:24rpx;font-weight:650}.visit-info>view:nth-child(2) text:last-child{color:#8490a4;font-size:19rpx}.visit-info>text{color:#17a47d;font-size:19rpx}.chat{height:720rpx;margin-top:20rpx}.message{display:flex;align-items:flex-start;margin:22rpx 0}.message>text{max-width:72%;padding:20rpx 22rpx;border-radius:8rpx 24rpx 24rpx 24rpx;background:#fff;box-shadow:0 8rpx 25rpx rgba(43,89,154,.08);font-size:23rpx;line-height:1.65;white-space:pre-wrap}.ai-avatar{width:62rpx;height:62rpx;margin-right:12rpx;border-radius:20rpx;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#5de1cb,#2879f3);color:#fff;font-size:21rpx}.message.user{justify-content:flex-end}.message.user>text{border-radius:24rpx 8rpx 24rpx 24rpx;background:#3b82f4;color:#fff}.message.system{justify-content:center}.message.system>text{max-width:88%;background:#eaf3ff;color:#49698f}.composer{position:fixed;left:0;right:0;bottom:0;padding:18rpx 24rpx calc(env(safe-area-inset-bottom) + 18rpx);display:flex;gap:13rpx;background:#fff}.composer input{flex:1;height:72rpx;padding:0 22rpx;border-radius:25rpx;background:#f2f5fa;font-size:23rpx}.composer>view{width:110rpx;border-radius:24rpx;display:flex;align-items:center;justify-content:center;background:#2878ff;color:#fff;font-size:23rpx}</style>
