<script setup lang="ts">
import { ref, onUnmounted } from 'vue';import PageHeader from '../../components/PageHeader.vue';import{aiApi,recognizeVoice,type TriageResult}from'../../api/ai';import{currentPatient}from'../../stores/session'
const symptom=ref('');const recording=ref(false);const recognizing=ref(false);const analyzing=ref(false);const result=ref<TriageResult|null>(null)
const tags=['头痛','发热','咳嗽','胸闷','腹痛','皮肤瘙痒','关节疼痛','睡眠不佳']
const recorder=uni.getRecorderManager()
recorder.onStop(async event=>{recording.value=false;recognizing.value=true;uni.showLoading({title:'正在识别'});try{const text=await recognizeVoice(event.tempFilePath);symptom.value=symptom.value?`${symptom.value}、${text}`:text;uni.showToast({title:'识别成功',icon:'success'})}catch(error){uni.showToast({title:error instanceof Error?error.message:'语音识别失败',icon:'none'})}finally{recognizing.value=false;uni.hideLoading()}})
recorder.onError(()=>{recording.value=false;uni.showToast({title:'录音失败，请检查麦克风权限',icon:'none'})})
function toggleRecord(){if(recognizing.value)return;if(recording.value){recorder.stop()}else{uni.authorize({scope:'scope.record',success:()=>{recording.value=true;recorder.start({duration:60000,sampleRate:16000,numberOfChannels:1,encodeBitRate:48000,format:'PCM',frameSize:50})},fail:()=>uni.showModal({title:'需要麦克风权限',content:'请在小程序设置中允许使用麦克风。',showCancel:false})})}}
function addTag(tag:string){symptom.value=symptom.value?`${symptom.value}、${tag}`:tag}
async function analyze(){if(!symptom.value.trim()){uni.showToast({title:'请描述您的症状',icon:'none'});return}analyzing.value=true;result.value=null;try{const data=await aiApi.triage(symptom.value.trim(),currentPatient.value?.patientId);if(data.isOutOfScope){uni.showToast({title:data.outOfScopeMessage||'请输入与健康相关的症状',icon:'none'});return}result.value=data}catch{}finally{analyzing.value=false}}
function register(){if(!result.value)return;uni.navigateTo({url:`/pages/registration/index?departmentId=${result.value.recommendedDepartmentId||''}&department=${encodeURIComponent(result.value.recommendedDepartment||'')}`})}
onUnmounted(()=>{if(recording.value)recorder.stop()})
</script>
<template><view class="page-shell triage-page"><PageHeader title="AI 智能导诊" subtitle="描述症状，为您匹配合适科室"/><view class="ai-hero"><view class="ai-orbit"><text>AI</text></view><view><text class="hero-title">您好，我是熙康导诊助手</text><text class="hero-desc">请告诉我哪里不舒服，我会结合症状为您推荐就诊科室。</text></view></view><view class="input-card card"><view class="input-head"><text>症状描述</text><text>{{symptom.length}}/300</text></view><textarea v-model="symptom" maxlength="300" placeholder="例如：头痛两天，伴随恶心，晚上症状更明显……"/><view class="input-actions"><view class="voice" :class="{recording}" @tap="toggleRecord"><view class="mic">{{recording?'■':'●'}}</view><text>{{recording?'点击结束录音':'语音输入'}}</text></view><text class="clear" @tap="symptom=''">清空</text></view></view><view class="tag-card card"><text class="block-title">常见症状</text><view class="tags"><text v-for="tag in tags" :key="tag" @tap="addTag(tag)">{{tag}}</text></view></view><button class="analyze-btn" :loading="analyzing" @tap="analyze">{{analyzing?'AI 正在分析':'开始智能导诊'}}</button><view v-if="result" class="result-card card"><view class="result-top"><view class="result-icon">科</view><view><text class="result-label">推荐就诊科室</text><text class="result-name">{{result.recommendedDepartment||'综合门诊'}}</text></view><text class="match">{{result.confidenceLevel==='high'?'高可信度':'AI 推荐'}}</text></view><text class="reason">{{result.departmentReason||result.urgencyAdvice||'建议前往推荐科室进一步评估。'}}</text><view class="tips"><text>就诊建议</text><text v-for="item in result.redFlags||[]" :key="item">• {{item}}</text><text v-if="result.selfCareAdvice">• {{result.selfCareAdvice}}</text></view><button @tap="register">查看科室号源</button></view><view class="safe-tip">AI 导诊仅提供就医方向参考，不能替代医生诊断</view></view></template>
<style scoped lang="scss">.triage-page{padding-left:24rpx;padding-right:24rpx}.ai-hero{padding:28rpx 20rpx 34rpx;display:flex;align-items:center;gap:22rpx}.ai-orbit{width:100rpx;height:100rpx;border-radius:32rpx;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#5de1cb,#2577f3);box-shadow:0 15rpx 35rpx rgba(43,131,216,.25);color:#fff;font-size:31rpx;font-weight:800}.ai-hero>view:last-child{flex:1;display:flex;flex-direction:column;gap:12rpx}.hero-title{font-size:30rpx;font-weight:750}.hero-desc{color:#6d7c96;font-size:22rpx;line-height:1.6}.input-card{padding:27rpx}.input-head{display:flex;justify-content:space-between;font-size:27rpx;font-weight:700}.input-head text:last-child{color:#9aa4b5;font-size:20rpx;font-weight:400}.input-card textarea{width:100%;height:200rpx;margin-top:20rpx;padding:20rpx;border-radius:20rpx;background:#f5f8fd;font-size:25rpx;line-height:1.65}.input-actions{display:flex;align-items:center;justify-content:space-between;margin-top:18rpx}.voice{display:flex;align-items:center;gap:10rpx;padding:12rpx 20rpx;border-radius:24rpx;background:#e9f3ff;color:#2878ff;font-size:22rpx}.voice.recording{background:#fff0f1;color:#f04b59}.mic{width:28rpx;height:28rpx;display:flex;align-items:center;justify-content:center}.clear{color:#8c97a9;font-size:22rpx}.tag-card{margin-top:20rpx;padding:25rpx}.block-title{font-size:27rpx;font-weight:700}.tags{display:flex;flex-wrap:wrap;gap:16rpx;margin-top:20rpx}.tags text{padding:11rpx 22rpx;border-radius:25rpx;background:#f1f6fd;color:#4e668d;font-size:22rpx}.analyze-btn{margin-top:24rpx;height:90rpx;border-radius:25rpx;background:linear-gradient(100deg,#2773f1,#59a0ff);color:#fff;font-size:29rpx;box-shadow:0 12rpx 28rpx rgba(40,120,255,.25)}.result-card{margin-top:24rpx;padding:27rpx}.result-top{display:flex;align-items:center}.result-icon{width:72rpx;height:72rpx;border-radius:22rpx;display:flex;align-items:center;justify-content:center;background:linear-gradient(145deg,#72c7ff,#3476ef);color:#fff;font-size:29rpx}.result-top>view:nth-child(2){flex:1;margin-left:17rpx;display:flex;flex-direction:column}.result-label{color:#79869d;font-size:20rpx}.result-name{margin-top:5rpx;font-size:31rpx;font-weight:750}.match{padding:7rpx 12rpx;border-radius:16rpx;background:#e7f8f2;color:#18a37e;font-size:19rpx}.reason{display:block;margin-top:22rpx;color:#52627e;font-size:23rpx;line-height:1.7}.tips{margin-top:20rpx;padding:20rpx;border-radius:18rpx;display:flex;flex-direction:column;gap:9rpx;background:#f5f8fd;color:#66748c;font-size:21rpx}.tips text:first-child{color:#1c3159;font-weight:700}.result-card button{margin-top:20rpx;background:#2878ff;color:#fff}.safe-tip{text-align:center;margin:25rpx 0;color:#9aa4b4;font-size:19rpx}</style>
